### ISSUE TITLE
Why is the root node not displayed?

### ISSUE THREAD

**Issue by dominikduda** [lmeijvogel/vim-yaml-helper#5]
For example in this situation:
![image](https://cloud.githubusercontent.com/assets/14922999/24494021/18546f04-1531-11e7-8d78-ad1fc4ada073.png)
`:YamlGetFullPath` displays `locales.de`. IMO it should display `en.locales.de`.

Edit:
I took quick look at the source code and thats probably caused by breaking path finding loop when there is no parent (and the root node does not have parent).

From my understanding easy fix would be adding `call add(keys, key)` below [this line](https://github.com/lmeijvogel/vim-yaml-helper/blob/master/plugin/vim-yaml-helper.vim#L33).

Edit 2:
I tested it and it works; I will create pull request in the evening.

**Comment by lmeijvogel** [comment]
Hey,

I actually did that for a reason: I only use it for translations for Rails and in that case, I'm never interested in the root node, since that specifies the language, so if I'm using a translation from:
```yaml
en:
  messages:
    login: "Please login"
```

I want this to go in the relevant view:
```ruby
<%= I18n::t('messages.login') %>
```
so Rails can handle the rest.

The same for the other way around: Say that I encounter a translation in a view: `t('messages.login.failed')`, and I want to locate it in the corresponding yml-file, then I want it to search _below_ the root node `en`, otherwise it will fail, since `"en" != "messages"` and there are no other keys on the root level.

So a PR is of course welcome, but please make the behavior configurable.

**Comment by dominikduda** [comment]
I understand your use case, but recently I encountered some task related to `phraseapp` software and shortly saying I had to deal with many locales in a single YAML file.

I will add some `g:vim-yaml-helper-show-root` variable which will be responsible for showing root in the output. It will defaults to 0 so for existing users behavior will not change.

I'm not promising that this will happen today, but surely in near future. :)
